### ISSUE TITLE
mmcount plugin is broken (msgGetCEEPropJSON was removed in Oct. 2013)

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#129]
Hi,

the _mmcount_ message modification plugin is broken since commit eb9adf9baad5dca9dc2f30f45dc6eaf7607ac8f8 and c0f44743898954aee7f846ce630280a80297b80d:

```
mmcount.c:289:2: warning: implicit declaration of function 'msgGetCEEPropJSON' [-Wimplicit-function-declaration]
  if(msgGetCEEPropJSON(pMsg, estr, &keyjson) != RS_RET_OK) {
  ^
```

So if somebody is using the mmcount plugin since that commit, rsyslog will crash at runtime.

3 Options:
- Bring back _msgGetCEEPropJSON_
- Update the plugin (because it seems to be a user contribution contact the author)
- Remove the plugin ;)
