### PR TITLE
lmsig_ksils12: fixing issues 2517 and 2621

### LINKED ISSUE #2517: ksi-ls12 breaks make
### Expected behavior
When running rsyslog configure  with `--enable-ksi-ls12` it the `make` should work fine
Was working fine in 8.32.0.

### Actual behavior

From buildlog:

```
  CC     lmsig_ksi_ls12_la-lmsig_ksi-ls12.lo
  CC     lmsig_ksi_ls12_la-lib_ksils12.lo
lib_ksils12.c:65: error: redefinition of typedef 'uchar'
typedefs.h:49: note: previous declaration of 'uchar' was here
lib_ksils12.c: In function 'ksiCreateFile':
lib_ksils12.c:557: warning: ignoring return value of 'fwrite', declared with attribute warn_unused_result
make[2]: *** [lmsig_ksi_ls12_la-lib_ksils12.lo] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/rsyslog-8.33.1/runtime'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/rsyslog-8.33.1'
make: *** [all] Error 2
```

### Steps to reproduce the behavior

```
./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --target=x86_64-redhat-linux-gnu --program-prefix= --prefix=/usr --exec-prefix= --bindir=/bin --sbindir=/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/lib64 --libexecdir=/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-static --disable-testbench --enable-uuid --enable-elasticsearch --enable-omkafka --enable-imkafka --enable-kafka-static --enable-usertools --enable-ksi-ls12 --enable-gnutls --enable-imfile --enable-impstats --enable-imptcp --enable-libdbi --enable-mail --enable-mysql --enable-omprog --enable-omudpspoof --enable-omuxsock --enable-omstdout --enable-pgsql --enable-pmlastmsg --enable-relp --enable-snmp --enable-unlimited-select --enable-mmjsonparse --enable-mmnormalize --enable-mmanon --enable-mmutf8fix --enable-mail --enable-mmfields --enable-mmpstrucdata --enable-mmsequence --enable-mmrm1stspace --enable-pmaixforwardedfrom --enable-pmciscoios --disable-liblogging-stdlog
make
```

### Environment.
- rsyslog version: 8.33.1
- platform: CentOS6 / EL6

### PR DESCRIPTION
**Pull request by allanpark**
closes #2517 
see also #2621

### CODE REVIEW

**Comment by rgerhards** [comment]
@allanpark can you plaese rebase to current master. We needed to change some CI ressources and this is why you get those failures.

**Comment by rgerhards** [comment]
@allanpark thx. The ubuntu16 build failed now because we enabled the static analyzer. So you can now review the issues (report link in failed build log). I'll disable the static analyzer again as otherwise all PRs will fail. Will re-enable when you push the next change set.

**Comment by rgerhards** [comment]
unfortunately the static analyzer still complains: http://ubuntu16.rsyslog.com/18-04-13_08-01-28/

**Comment by rgerhards** [comment]
It looks like the push did not go through (-f forgotten?).

**Comment by rgerhards** [comment]
excellent, all looks well! Thanks for the hard work. I'll merge soon.
