### ISSUE TITLE
runtime/rsyslog.h:519:36: error: variable ‘iRet’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]

### ISSUE THREAD

**Issue by Whissi** [rsyslog/rsyslog#1581]
```
libtool: compile:  x86_64-pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../.. -I../.. -pthread -I../../runtime -I../.. -I../../grammar -I/usr/include/libfastjson -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -fno-strict-aliasing -Wall -Wextra -Wundef -Wnested-externs -Wwrite-strings -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wno-unused-parameter -Wno-missing-field-initializers -Wdeclaration-after-statement -Wformat=2 -Wold-style-definition -Wcast-align -Wformat-nonliteral -Wformat-security -Wsign-compare -Wstrict-aliasing -Wshadow -Winline -Wpacked -Wmissing-format-attribute -Wmissing-noreturn -Winit-self -Wmissing-include-dirs -Wunused-but-set-variable -Warray-bounds -Wimplicit-function-declaration -Wreturn-type -Wswitch-enum -Wswitch-default -Werror -Wno-suggest-attribute=format -Wno-error=unused-parameter -Wno-error=missing-field-initializers -O2 -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt -Werror=format-security -frecord-gcc-switches -ggdb -c imfile.c  -fPIC -DPIC -o .libs/imfile_la-imfile.o
In file included from imfile.c:45:0:
imfile.c: In function ‘pollFile’:
../../runtime/rsyslog.h:519:36: error: variable ‘iRet’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Werror=clobbered]
 #define DEFiRet BEGINfunc rsRetVal iRet = RS_RET_OK
                                    ^
imfile.c:713:2: note: in expansion of macro ‘DEFiRet’
  DEFiRet;
  ^~~~~~~
cc1: all warnings being treated as errors
```

Introduced by commit 5c686c8adcc473cbdbb14e4b2d736f9123210ee6

**Comment by rgerhards** [comment]
which compiler/version do you use? I ask because CI obviously doesn't catch this.

**Comment by Whissi** [comment]
I was wondering, too:
```
Portage 2.3.5 (python 3.6.1-final-0, default/linux/amd64/13.0, gcc-6.3.0, glibc-2.25, 4.11.0-gentoo x86_64)
=================================================================
System uname: Linux-4.11.0-gentoo-x86_64-Intel-R-_Core-TM-_i7-3770K_CPU_@_3.50GHz-with-gentoo-2.3
KiB Mem:     8136900 total,   6889936 free
KiB Swap:    1048572 total,   1048572 free
Timestamp of repository gentoo: Tue, 23 May 2017 09:02:13 +0000
sh dash 0.5.9.1-r1
ld GNU ld (Gentoo 2.28 p1.0) 2.28
app-shells/bash:          4.4_p12::gentoo
dev-java/java-config:     2.2.0-r3::gentoo
dev-lang/perl:            5.24.1-r1::gentoo
dev-lang/python:          2.7.13::gentoo, 3.4.6::gentoo, 3.5.3::gentoo, 3.6.1-r1::gentoo
dev-util/cmake:           3.8.1::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.3::gentoo
sys-apps/openrc:          0.26.2::gentoo
sys-apps/sandbox:         2.10-r4::gentoo
sys-devel/autoconf:       2.69-r3::gentoo
sys-devel/automake:       1.13.4-r1::gentoo, 1.15-r2::gentoo
sys-devel/binutils:       2.28::gentoo
sys-devel/gcc:            6.3.0::gentoo
sys-devel/gcc-config:     1.8-r1::gentoo
sys-devel/libtool:        2.4.6-r4::gentoo
sys-devel/make:           4.2.1-r1::gentoo
sys-kernel/linux-headers: 4.10::gentoo (virtual/os-headers)
sys-libs/glibc:           2.25::gentoo
```

**Comment by rgerhards** [comment]
Could you double check against master? I think I fixed it but forgot to close the bug.

**Comment by Whissi** [comment]
Yes, cannot reproduce anymore against current git master (326af71fbdb3a7347d8147b49b8391f40005b4e0).
