### ISSUE TITLE
Rsyslog8 8.2402.0 does not build with LibreSSL 3.8.3

### ISSUE THREAD

**Issue by davehayes** [rsyslog/rsyslog#5353]
This build failure is  from a build log for FreeBSD 13.2-STABLE :

```
cc -DHAVE_CONFIG_H -I. -I.. -pthread -I../runtime -I.. -I../grammar -O2 -pipe -I/usr/local/include -I/usr/local/include -I/usr/local/include -fstack-protector-strong -fno-strict-aliasing -I/usr/local/include/libfastjson -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Werror=implicit-function-declaration -g -I /usr/local/include -I/usr/local/include -I/usr/local/include -O2 -pipe -I/usr/local/include -I/usr/local/include -I/usr/local/include -fstack-protector-strong -fno-strict-aliasing -W -Wall -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -g -MT lmnsd_ossl_la-net_ossl.lo -MD -MP -MF .deps/lmnsd_ossl_la-net_ossl.Tpo -c net_ossl.c  -fPIC -DPIC -o .libs/lmnsd_ossl_la-net_ossl.o
  net_ossl.c:482:3: error: unknown type name 'SSL_CONF_CTX'; did you mean 'SSL_AEAD_CTX'?
  ...
```
It seems that LibreSSL doesn't support SSL_CONF_CTX ideas. Looking through net_ossl.c, I find there was support at one time:

```
> grep -ni OPENSSL_VERSION_NUMBER work/rsyslog-8.2402.0/runtime/net_ossl.c
121:#if OPENSSL_VERSION_NUMBER < 0x10100000L
123:#endif /* OPENSSL_VERSION_NUMBER < 0x10100000L */
149:#if OPENSSL_VERSION_NUMBER < 0x10100000L
151:#endif /* OPENSSL_VERSION_NUMBER < 0x10100000L */
180:#if OPENSSL_VERSION_NUMBER < 0x10100000L
193:#if OPENSSL_VERSION_NUMBER >= 0x30000000L && !defined(LIBRESSL_VERSION_NUMBER)
306:#if OPENSSL_VERSION_NUMBER >= 0x30000000L && !defined(LIBRESSL_VERSION_NUMBER)
319:#	if OPENSSL_VERSION_NUMBER >= 0x10002000L
397:#if OPENSSL_VERSION_NUMBER >= 0x10002000L
398:#	if OPENSSL_VERSION_NUMBER <= 0x101010FFL
594:#if OPENSSL_VERSION_NUMBER >= 0x10002000L
618:#if OPENSSL_VERSION_NUMBER >= 0x10002000L
969:#if OPENSSL_VERSION_NUMBER >= 0x30000000L && !defined(LIBRESSL_VERSION_NUMBER)
990:#if OPENSSL_VERSION_NUMBER < 0x10100000L
1053:#if OPENSSL_VERSION_NUMBER >= 0x10100000L
1113:#endif // OPENSSL_VERSION_NUMBER >= 0x10100000L
1135:#if OPENSSL_VERSION_NUMBER >= 0x30000000L && !defined(LIBRESSL_VERSION_NUMBER)
1139:#endif // OPENSSL_VERSION_NUMBER >= 0x10100000L
1180:#if OPENSSL_VERSION_NUMBER >= 0x10100000L
```

Perhaps the support is incomplete? Please advise, I am willing to apply patches and test fairly quickly. Thanks in advance.

**Comment by infracaninophile** [comment]
This is related to #5342, and the patch from that issue appears to fix compilation against libressl on FreeBSD.

**Comment by alorbach** [comment]
That SSL_CONF_CTX part needs to be left out using conditional compilation. Due the recent changes for the new DTLS modules, I had to relocate shared OpenSSL code and this issue was caused by these changes unintentionally.

I will take care on this issue and provide a patch ASAP.
