### ISSUE TITLE
Rsyslog <omkafka module> is not working in ubuntu 16.04

### ISSUE THREAD

**Issue by saithejareddy** [rsyslog/rsyslog#4217]
I installed rsyslog from source and installed the required dependencies(librdkafka as well).
`./configure --enable-omkafka` also worked fine..
But make and make install are throwing errors in ubuntu 16.04
Attaching errors for your reference:
`make[2]: Entering directory '/opt/rsyslog-8.2002.0/plugins/omkafka'
  CC       omkafka_la-omkafka.lo
omkafka.c: In function 'createTopic':
omkafka.c:438:21: error: implicit declaration of function 'rd_kafka_last_error' [-Werror=implicit-function-declaration]
    rd_kafka_err2str(rd_kafka_last_error()));
                     ^
omkafka.c:438:4: warning: nested extern declaration of 'rd_kafka_last_error' [-Wnested-externs]
    rd_kafka_err2str(rd_kafka_last_error()));
    ^
omkafka.c: In function 'do_rd_kafka_destroy':
omkafka.c:1102:28: error: implicit declaration of function 'rd_kafka_flush' [-Werror=implicit-function-declaration]
    const int flushStatus = rd_kafka_flush(pData->rk, pData->closeTimeout);
                            ^
omkafka.c:1102:4: warning: nested extern declaration of 'rd_kafka_flush' [-Wnested-externs]
    const int flushStatus = rd_kafka_flush(pData->rk, pData->closeTimeout);
    ^
omkafka.c: In function 'errorCallback':
omkafka.c:1181:20: error: 'RD_KAFKA_RESP_ERR__AUTHENTICATION' undeclared (first use in this function)
  } else if (err == RD_KAFKA_RESP_ERR__AUTHENTICATION) {
                    ^
omkafka.c:1181:20: note: each undeclared identifier is reported only once for each function it appears in
omkafka.c: In function 'openKafka':
omkafka.c:1290:27: warning: passing argument 1 of 'rd_kafka_conf_set_log_cb' from incompatible pointer type [-Wincompatible-pointer-types]
  rd_kafka_conf_set_log_cb(pData->rk, kafkaLogger);
                           ^
In file included from omkafka.c:40:0:
/usr/include/librdkafka/rdkafka.h:336:6: note: expected 'rd_kafka_conf_t * {aka struct rd_kafka_conf_s *}' but argument is of type 'rd_kafka_t * {aka struct rd_kafka_s *}'
 void rd_kafka_conf_set_log_cb (rd_kafka_conf_t *conf,
      ^
cc1: some warnings being treated as errors
Makefile:550: recipe for target 'omkafka_la-omkafka.lo' failed
`

**Comment by saithejareddy** [comment]
![image](https://user-images.githubusercontent.com/50693675/76457148-404f4000-63fe-11ea-841a-30b77aa6c2ff.png)
