### ISSUE TITLE
omusrmsg seems not to work on RockyLinux

### ISSUE THREAD

**Issue by OmkarPokharkar** [rsyslog/rsyslog#6715]
### 📝 Description / What's on your mind:
The omusrmsg (built-in output module for writing to user terminals) is 
missing several required entry point functions, indicating an incomplete 
or corrupted build.

Error Messages from rsyslogd -dn:
- omusrmsg.c: entry point 'setModCnf' not present in module
- omusrmsg.c: entry point 'beginCnfLoad' not present in module
- omusrmsg.c: entry point 'doHUP' not present in module
- omusrmsg.c: entry point 'doHUPWrkr' not present in module
- omusrmsg.c: entry point 'SetShutdownImmdtPtr' not present in module
- omusrmsg.c: entry point 'beginTransaction' not present in module
- omusrmsg.c: entry point 'commitTransaction' not present in module
- omusrmsg.c: entry point 'endTransaction' not present in module

Steps to reproduce:
1. Install rsyslog 8.2512.0
2. Run: rsyslogd -dn 2>&1 | grep "entry point.*not present"
3. Expected: No errors
4. Actual: Multiple missing entry point errors for omusrmsg module

Impact:
Emergency messages to user terminals may not work correctly due to 
the incomplete module implementation.

### 💻 Environment (if applicable):
(If this issue relates to a specific setup or environment, please provide details. Otherwise, you can remove or leave this section blank.)

* **Rsyslog Version:**  8.2512.0``
* **Platform:** Rocky 8.10``
* **Deployment Method:**  host-os service``

### ➕ Additional Context:
Need this version specifically for the rocky 8.10. if this is duplicate issue or already fix please tell me the version which can be work with rocky 8.10

---
**Thank you for your contribution!**

**Comment by rgerhards** [comment]
This is correct behaviour. The `-d` switch enables debug messages. Most of them are status messages, not error messages. So the rsyslog core does rightfully tell that `omusrmsg` does not implement these optional callbacks. They are not needed for this simple module.

Please let me know if you see some real issue like a degradation.

**Comment by OmkarPokharkar** [comment]
emergency messages are not being broadcast over the login session it was working in centos based system but with rocky it is not working. In debug mode it was shown these logs.

following line should broadcast them but im not seeing any broadcast
# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

**Comment by rgerhards** [comment]
Ah, that that's the issue. My guess is the rocky linux SELinux policy blocks this. Are there any error messages from rsyslog?

**Comment by OmkarPokharkar** [comment]
Found the RCA new version works with systemd sessions to know the login session broadcast while older version was simpler with utmp. Systemd sessions are not accessible for the rsyslog to use, kind of selinux violation

**Comment by rgerhards** [comment]
This looks answered by the investigation in the thread.

The debug messages about missing `omusrmsg` entry points are not themselves errors. Those callbacks are optional, and simple built-in modules do not need to implement all of them.

The actual broadcast problem was later identified as a Rocky/systemd/SELinux session-access issue: newer behavior depends on systemd session information, and the process may be blocked from accessing it by local policy. That makes this a distro policy/configuration problem rather than evidence that `omusrmsg` is missing required entry points.

I am closing this as answered. If there is still a reproducible rsyslog-side failure after the SELinux/systemd policy issue is resolved, please update the issue with the current rsyslog version, SELinux denial/audit messages, and a minimal config.
