### ISSUE TITLE
[Bug]: Rsyslog 8.2412 fails to build with openssl 3.4.3 due to deprecated api (3.0) dependencies

### ISSUE THREAD

**Issue by derekatkins** [rsyslog/rsyslog#6310]
Trying to build RSyslog 8.2412 on a system with openssl 3.4.3.  When building, I get a bunch of errors due to usage of deprecated APIs.  Unlike issue #5362 this actually affects the build of rsyslog when you configure with --enable-openssl`.  The reason is that the Engine APIs are no longer built, and therefore not generally available, without jumping through additional hoops.  Apparently the "fix" is to switch to the Platform API.

```
net_ossl.c: In function 'osslGlblInit':
net_ossl.c:227:9: error: implicit declaration of function 'ENGINE_load_builtin_engines' [-Werror=implicit-function-declaration]
  227 |         ENGINE_load_builtin_engines();
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
net_ossl.c:227:9: warning: nested extern declaration of 'ENGINE_load_builtin_engines' [-Wnested-externs]
net_ossl.c:229:9: error: implicit declaration of function 'ENGINE_register_all_complete' [-Werror=implicit-function-declaration]
  229 |         ENGINE_register_all_complete();
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
net_ossl.c:229:9: warning: nested extern declaration of 'ENGINE_register_all_complete' [-Wnested-externs]
  CCLD     lmzlibw.la
net_ossl.c:232:30: error: implicit declaration of function 'ENGINE_get_first' [-Werror=implicit-function-declaration]
  232 |         ENGINE *osslEngine = ENGINE_get_first();
      |                              ^~~~~~~~~~~~~~~~
net_ossl.c:232:30: warning: nested extern declaration of 'ENGINE_get_first' [-Wnested-externs]
net_ossl.c:232:30: warning: initialization of 'ENGINE *' {aka 'struct engine_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
net_ossl.c:237:21: error: implicit declaration of function 'ENGINE_get_init_function' [-Werror=implicit-function-declaration]
  237 |                 if (ENGINE_get_init_function(osslEngine)) { // Check if engine is initialized
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~
net_ossl.c:237:21: warning: nested extern declaration of 'ENGINE_get_init_function' [-Wnested-externs]
  CCLD     lmnetstrms.la
net_ossl.c:238:37: error: implicit declaration of function 'ENGINE_get_id' [-Werror=implicit-function-declaration]
  238 |                         engine_id = ENGINE_get_id(osslEngine);
      |                                     ^~~~~~~~~~~~~
net_ossl.c:238:37: warning: nested extern declaration of 'ENGINE_get_id' [-Wnested-externs]
net_ossl.c:238:35: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  238 |                         engine_id = ENGINE_get_id(osslEngine);
      |                                   ^
net_ossl.c:239:39: error: implicit declaration of function 'ENGINE_get_name'; did you mean 'EVP_KEM_get0_name'? [-Werror=implicit-function-declaration]
  239 |                         engine_name = ENGINE_get_name(osslEngine);
      |                                       ^~~~~~~~~~~~~~~
      |                                       EVP_KEM_get0_name
net_ossl.c:239:39: warning: nested extern declaration of 'ENGINE_get_name' [-Wnested-externs]
net_ossl.c:239:37: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  239 |                         engine_name = ENGINE_get_name(osslEngine);
      |                                     ^
  CCLD     lmnet.la
net_ossl.c:242:30: error: implicit declaration of function 'ENGINE_get_next' [-Werror=implicit-function-declaration]
  242 |                 osslEngine = ENGINE_get_next(osslEngine);
      |                              ^~~~~~~~~~~~~~~
net_ossl.c:242:30: warning: nested extern declaration of 'ENGINE_get_next' [-Wnested-externs]
net_ossl.c:242:28: warning: assignment to 'ENGINE *' {aka 'struct engine_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
  242 |                 osslEngine = ENGINE_get_next(osslEngine);
      |                            ^
net_ossl.c:245:9: error: implicit declaration of function 'ENGINE_free' [-Werror=implicit-function-declaration]
  245 |         ENGINE_free(osslEngine);
      |         ^~~~~~~~~~~
net_ossl.c:245:9: warning: nested extern declaration of 'ENGINE_free' [-Wnested-externs]
  CCLD     lmtcpclt.la
net_ossl.c: In function 'osslGlblExit':
net_ossl.c:254:9: error: implicit declaration of function 'ENGINE_cleanup'; did you mean 'EVP_PBE_cleanup'? [-Werror=implicit-function-declaration]
  254 |         ENGINE_cleanup();
      |         ^~~~~~~~~~~~~~
      |         EVP_PBE_cleanup
net_ossl.c:254:9: warning: nested extern declaration of 'ENGINE_cleanup' [-Wnested-externs]
  CCLD     lmnsd_ptcp.la
net_ossl.c: In function 'net_ossl_init_engine':
net_ossl.c:1155:34: error: implicit declaration of function 'ENGINE_get_default_RSA' [-Werror=implicit-function-declaration]
 1155 |         ENGINE *default_engine = ENGINE_get_default_RSA();
      |                                  ^~~~~~~~~~~~~~~~~~~~~~
net_ossl.c:1155:34: warning: nested extern declaration of 'ENGINE_get_default_RSA' [-Wnested-externs]
net_ossl.c:1155:34: warning: initialization of 'ENGINE *' {aka 'struct engine_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
net_ossl.c:1157:27: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 1157 |                 engine_id = ENGINE_get_id(default_engine);
      |                           ^
net_ossl.c:1158:29: warning: assignment to 'const char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 1158 |                 engine_name = ENGINE_get_name(default_engine);
      |                             ^
net_ossl.c:1169:34: error: implicit declaration of function 'ENGINE_by_id' [-Werror=implicit-function-declaration]
 1169 |                 default_engine = ENGINE_by_id((char *)glbl.GetDfltOpensslEngine(runConf));
      |                                  ^~~~~~~~~~~~
net_ossl.c:1169:34: warning: nested extern declaration of 'ENGINE_by_id' [-Wnested-externs]
net_ossl.c:1169:32: warning: assignment to 'ENGINE *' {aka 'struct engine_st *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
 1169 |                 default_engine = ENGINE_by_id((char *)glbl.GetDfltOpensslEngine(runConf));
      |                                ^
net_ossl.c:1170:39: error: implicit declaration of function 'ENGINE_init' [-Werror=implicit-function-declaration]
 1170 |                 if (default_engine && ENGINE_init(default_engine)) {
      |                                       ^~~~~~~~~~~
net_ossl.c:1170:39: warning: nested extern declaration of 'ENGINE_init' [-Wnested-externs]
net_ossl.c:1172:25: error: implicit declaration of function 'ENGINE_set_default_DSA' [-Werror=implicit-function-declaration]
 1172 |                         ENGINE_set_default_DSA(default_engine);
      |                         ^~~~~~~~~~~~~~~~~~~~~~
net_ossl.c:1172:25: warning: nested extern declaration of 'ENGINE_set_default_DSA' [-Wnested-externs]
net_ossl.c:1173:25: error: implicit declaration of function 'ENGINE_set_default_ciphers' [-Werror=implicit-function-declaration]
 1173 |                         ENGINE_set_default_ciphers(default_engine);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
net_ossl.c:1173:25: warning: nested extern declaration of 'ENGINE_set_default_ciphers' [-Wnested-externs]
net_ossl.c:1180:25: error: implicit declaration of function 'ENGINE_finish' [-Werror=implicit-function-declaration]
 1180 |                         ENGINE_finish(default_engine);
      |                         ^~~~~~~~~~~~~
net_ossl.c:1180:25: warning: nested extern declaration of 'ENGINE_finish' [-Wnested-externs]
```

**Comment by rgerhards** [comment]
@derekatkins thx for notifying.

I would appreciate if you could also check out https://github.com/rsyslog/rsyslog/pull/6513

Note that this PR builds on work previously done poit 8.2512, so do not wonder why it is only a configure check.
