### ISSUE TITLE
Errors with TLS connections in 8.15

### ISSUE THREAD

**Issue by Kryai** [rsyslog/rsyslog#732]
After upgrading to 8.15 I have started to get errors in my logs on my RHEL 6.5 rsyslog server that uses TLS.

```
Jan 11 13:01:02 syslog.err rsyslog_server rsyslogd-2078: unexpected GnuTLS error -50 in nsd_gtls.c:530: The request is invalid.  [v8.15.0 try http://www.rsyslog.com/e/2078 ]
Jan 11 13:01:02 syslog.err rsyslog_server rsyslogd-2089: netstream session 0x7f77a8190520 from 172.30.108.105 will be closed due to error  [v8.15.0 try http://www.rsyslog.com/e/2089 ]

Jan 11 13:02:02 syslog.err rsyslog_client rsyslogd-2078: unexpected GnuTLS error -53 in nsd_gtls.c:1628: Error in the push function.  [v8.11.0 try http://www.rsyslog.com/e/2078 ]
Jan 11 13:02:02 syslog.info rsyslog_client rsyslogd-2359: action 'action 8' resumed (module 'builtin:omfwd') [v8.11.0 try http://www.rsyslog.com/e/2359 ]
Jan 11 13:02:02 syslog.info rsyslog_client rsyslogd-2359: action 'action 8' resumed (module 'builtin:omfwd') [v8.11.0 try http://www.rsyslog.com/e/2359 ]
```

I've narrowed down the issue to the following commit in 8.15
https://github.com/rsyslog/rsyslog/commit/1394e0bec2373e85e003b7320c6d12870424d483

Reverting that commit, I've been error-free for a day now, previously errors would be generated hourly. I'm not knowledgeable enough to understand the full extent of the commit, and so further investigation will be required. I can help test any changes as needed.

**Comment by alorbach** [comment]
Strange, I don't see how the commit hould cause these unexpected TLS error's. 
A full debuglog would be helpful.

**Comment by dbray925** [comment]
I am seeing this exact same error, repeatedly throughout the day. I was lucky enough to capture a debug entry as well:

rsyslogd-2078: unexpected GnuTLS error -50 in nsd_gtls.c:530: The request is invalid.  [v8.16.0 try http://www.rsyslog.com/e/2078 ]
rsyslogd-2089: netstream session 0x7f7afc5e8e30 from IP.REMOVED. will be closed due to error  [v8.16.0 try http://www.rsyslog.com/e/2089 ]


```
7936.888488942:main Q:Reg/w0  : Action 6 transitioned to state: rdy
7936.888493091:main Q:Reg/w0  : Action 6 transitioned to state: itx
7936.888497624:main Q:Reg/w0  : Action 6 transitioned to state: rdy
7936.888501119:main Q:Reg/w0  : actionCommit, in retry loop, iRet 0
7936.888504560:main Q:Reg/w0  : processBATCH: batch of 7 elements has been processed
7936.888508344:main Q:Reg/w0  : regular consumer finished, iret=0, szlog 1 sz phys 8
7936.888512436:main Q:Reg/w0  : DeleteProcessedBatch: we deleted 7 objects and enqueued 0 objects
7936.888516063:main Q:Reg/w0  : doDeleteBatch: delete batch from store, new sizes: log 1, phys 1
7936.888519893:main Q:Reg/w0  : processBATCH: batch of 1 elements must be processed
7936.888523432:main Q:Reg/w0  : processBATCH: next msg 0: unexpected GnuTLS error -53 in nsd_gtls.c:1639: Error in the push function.  [v8.16.0 try http://www.rsyslog.com/e/2078 ]
```

Any other information I can provide to help with this?
