### ISSUE TITLE
rsyslog fails to build on macOS

### ISSUE THREAD

**Issue by fxcoudert** [rsyslog/rsyslog#1495]
Some more errors from building rsyslog on macOS, and associated patches:

```
mmexternal.c:37:10: fatal error: 'wait.h' file not found
```

is fixed by this patch:

```
--- plugins/mmexternal/mmexternal.c.old	2017-04-02 16:42:07.000000000 +0200
+++ plugins/mmexternal/mmexternal.c	2017-04-02 16:42:15.000000000 +0200
@@ -31,7 +31,7 @@
 #include <errno.h>
 #include <unistd.h>
 #include <fcntl.h>
-#if defined(_AIX) || defined(__FreeBSD__) 
+#if defined(_AIX) || defined(__FreeBSD__) || defined(__APPLE__)
 #include <sys/wait.h>
 #else
 #include <wait.h>
```

----

```
lookup.c:961:35: error: too many arguments to function call, expected 1, have 2
        pthread_setname_np(lu->reloader, reloader_thd_name);
```

This assumes Linux-style `pthread_setname_np`, which has different prototype from macOS (and that of many other BSD). Given that `pthread_setname_np` has many different prototypes in different OSes, the configure check should check not only its presence but whether it has the expected Linux-only prototype.

----

```
  CCLD     msggen
ld: unknown option: --whole-archive
```

is fixed in `tools/Makefile.am` by extending the `if AIX` to other systems with non-GNU linkers (and same thing for `rscryutil_LDFLAGS`).

**Comment by PascalWithopf** [comment]
Hi,
I started to integrate building rsyslog on macOS into travis, but I don't know much about it.
Could you tell me how it is possible to install packages.
This is my current status:
https://travis-ci.org/PascalWithopf/rsyslog/jobs/221369367

**Comment by rgerhards** [comment]
It looks like this build on 8.27.0. See #1538 for more info.
