### ISSUE TITLE
ksi-ls12 breaks make

### ISSUE THREAD

**Issue by friedl** [rsyslog/rsyslog#2517]
### Expected behavior
When running rsyslog configure  with `--enable-ksi-ls12` it the `make` should work fine
Was working fine in 8.32.0.

### Actual behavior

From buildlog:

```
  CC     lmsig_ksi_ls12_la-lmsig_ksi-ls12.lo
  CC     lmsig_ksi_ls12_la-lib_ksils12.lo
lib_ksils12.c:65: error: redefinition of typedef 'uchar'
typedefs.h:49: note: previous declaration of 'uchar' was here
lib_ksils12.c: In function 'ksiCreateFile':
lib_ksils12.c:557: warning: ignoring return value of 'fwrite', declared with attribute warn_unused_result
make[2]: *** [lmsig_ksi_ls12_la-lib_ksils12.lo] Error 1
make[2]: Leaving directory '/builddir/build/BUILD/rsyslog-8.33.1/runtime'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/builddir/build/BUILD/rsyslog-8.33.1'
make: *** [all] Error 2
```

### Steps to reproduce the behavior

```
./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --target=x86_64-redhat-linux-gnu --program-prefix= --prefix=/usr --exec-prefix= --bindir=/bin --sbindir=/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/lib64 --libexecdir=/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-static --disable-testbench --enable-uuid --enable-elasticsearch --enable-omkafka --enable-imkafka --enable-kafka-static --enable-usertools --enable-ksi-ls12 --enable-gnutls --enable-imfile --enable-impstats --enable-imptcp --enable-libdbi --enable-mail --enable-mysql --enable-omprog --enable-omudpspoof --enable-omuxsock --enable-omstdout --enable-pgsql --enable-pmlastmsg --enable-relp --enable-snmp --enable-unlimited-select --enable-mmjsonparse --enable-mmnormalize --enable-mmanon --enable-mmutf8fix --enable-mail --enable-mmfields --enable-mmpstrucdata --enable-mmsequence --enable-mmrm1stspace --enable-pmaixforwardedfrom --enable-pmciscoios --disable-liblogging-stdlog
make
```

### Environment.
- rsyslog version: 8.33.1
- platform: CentOS6 / EL6

**Comment by rgerhards** [comment]
@allanpark Can you reproduce this?

**Comment by allanpark** [comment]
Yes, I can reproduce it and also supply a patch.

**Comment by rgerhards** [comment]
issue depending on this one: https://github.com/rsyslog/rsyslog/issues/2621

**Comment by rgerhards** [comment]
@allanpark do you have any plans when a patch may come up? Or should I have a look at it?

**Comment by rgerhards** [comment]
No problem at all. I'll arm the static analyzer when the PR comes up ;-)
