### ISSUE TITLE
Build fails with msg.c:4091: error: json_tokener_errors undeclared (first use in this function)

### ISSUE THREAD

**Issue by alexjfisher** [rsyslog/rsyslog#143]
Using latest v8-stable.  Build script is below.  This is a recent regression as this process worked with 8.4.0(after applying fix for https://github.com/rsyslog/rsyslog/issues/117).

```
#!/bin/bash
set -e

/bin/rm -rf BUILD84x /opt/rsyslog-8.4x
mkdir BUILD84x
cd BUILD84x

tar xzf ../librelp-1.2.7.tar.gz
cd librelp-1.2.7

./configure --prefix=/opt/rsyslog-8.4x
make
make install
cd ../

tar xzf ../liblogging-1.0.4.tar.gz
cd liblogging-1.0.4
./configure --prefix=/opt/rsyslog-8.4x --enable-journal=no
make
make install
cd ../

tar xzf ../libestr-0.1.9.tar.gz
cd libestr-0.1.9
./configure --prefix=/opt/rsyslog-8.4x
make
make install
cd ../

tar xzf ../json-c-0.12-20140410.tar.gz
cd json-c-json-c-0.12-20140410
./configure --prefix=/opt/rsyslog-8.4x
make
make install
cd ../

git clone https://github.com/rsyslog/rsyslog.git
cd rsyslog
git checkout v8-stable
autoreconf -fvi
CFLAGS="-g3 -ggdb" PKG_CONFIG_PATH=/opt/rsyslog-8.4x/lib/pkgconfig ./configure --prefix=/opt/rsyslog-8.4x --enable-relp=yes --enable-static
make
make install
```
